### ISSUE TITLE
Add support for VuePress>=1.0

### ISSUE THREAD

**Issue by seifertm** [pskordilakis/vuepress-tabs#6]
I tested your plugin with VuePress 0.14 and it works just fine. However, it seems to break using the alpha version of VuePress 1.0.0.

Do you have any intention of porting your tabs plugin to `vuepress@next`?

**Comment by pskordilakis** [comment]
Yes  I have already started working on porting it to VuePress 1.0.0.
A next release will be ready in the forthcoming days.

**Comment by seifertm** [comment]
Thank you! I pointed the folks from the linked VuePress issue here. I wanted to avoid that anyone starts working on a similar tabs plugin instead of contributing to this plugin, if possible. That's why I opened the issue.

**Comment by pskordilakis** [comment]
I could not make the plugin naming resolution to work with this package. However I created a new package that works with Vuepress 1.0 https://github.com/pskordilakis/vuepress-plugin-tabs.

**Comment by seifertm** [comment]
This is great news, thank you! I just integrated it into my site following the README without any issues.
